title: BadgerBots
description: A starter template for BadgerBots Docs
theme: just-the-docs

url: https://badger-bots.github.io
# aux_links:
#   Source Code: https://github.com/badger-bots/badger-bots.github.io

nav_external_links:
  - title: GitHub
    url: https://github.com/badger-bots

color_scheme: badgerbots

callouts:
  hint:
    title: 💡 Hint
    color: grey-md
    opacity: 0.25

  info:
    title: ℹ️ Info
    color: blue
    opacity: 0.2
  
  attention:
    title: ⚠️ Attention
    color: yellow
    opacity: 0.2

  caution:
    title: ❗️ Caution
    color: red
    opacity: 0.15

# logo: /assets/images/BadgerBots-Logo-250x250.png
# favicon_ico: /assets/images/BadgerBots-Logo-220x220.png
